global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: user-service
    metrics_path: /user-service/actuator/prometheus
    static_configs:
      - targets: ['apigateway-service:8000']
  - job_name: order-service
    metrics_path: /order-service/actuator/prometheus
    static_configs:
      - targets: ['apigateway-service:8000']
  - job_name: apigateway-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['apigateway-service:8000']